# Generated by Django 2.0.7 on 2018-07-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_requirements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='resource',
        ),
        migrations.AddField(
            model_name='subject',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='teaching_requirements.Resource'),
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
