# Generated by Django 2.0.7 on 2018-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_requirements', '0002_auto_20180727_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='n_students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='requirements',
        ),
        migrations.AddField(
            model_name='activity',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='teaching_requirements.Resource'),
        ),
    ]
