# Generated by Django 2.2.1 on 2019-05-28 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_requirements', '0006_auto_20190528_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='instructions',
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
